apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  creationTimestamp: null
  labels:
    branch: master
    build: "1"
    jenkins.io/pipelineType: build
    owner: jstrachan
    repository: nodey442
  name: node-pr
spec:
  params:
  - name: version
    value: 0.0.0-SNAPSHOT-master-1
  - name: build_id
    value: "1"
  pipelineRef:
    apiVersion: tekton.dev/v1alpha1
    name: node-pr
  podTemplate: {}
  resources:
  - name: node-pr
    resourceRef:
      apiVersion: tekton.dev/v1alpha1
      name: node-pr
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
