dapiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  creationTimestamp: null
  name: node-release
spec:
  params:
  - name: revision
    value: master
    #value: v1.0.1
  - name: url
    value: https://@github.com/jstrachan/nodey442.git
  type: git
