apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  creationTimestamp: null
  labels:
    branch: master
    build: "1"
    jenkins.io/pipelineType: build
    owner: jstrachan
    repository: nodey442
  name: jstrachan-nodey442-master-qrnkl-1
spec:
  params:
  - name: version
    value: 1.0.1
  - name: build_id
    value: "1"
  pipelineRef:
    apiVersion: tekton.dev/v1alpha1
    name: jstrachan-nodey442-master-qrnkl-1
  podTemplate: {}
  resources:
  - name: jstrachan-nodey442-master-qrnkl
    resourceRef:
      apiVersion: tekton.dev/v1alpha1
      name: jstrachan-nodey442-master-qrnkl
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
