apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  creationTimestamp: null
  labels:
    branch: master
    build: "1"
    jenkins.io/pipelineType: build
    jenkins.io/task-stage-name: from-build-pack
    owner: jstrachan
    repository: nodey442
  name: jstrachan-nodey442-master-qrnkl-from-build-pack-1
  namespace: jx
spec:
  inputs:
    params:
    - default: 1.0.1
      description: the version number for this pipeline which is used as a tag on
        docker images and helm charts
      name: version
      type: string
    - default: "1"
      description: the PipelineRun build number
      name: build_id
      type: string
    resources:
    - name: workspace
      targetPath: source
      type: git
  steps:
  - args:
    - step
    - git
    - merge
    - --verbose
    command:
    - jx
    env:
    - name: DOCKER_REGISTRY
      valueFrom:
        configMapKeyRef:
          key: docker.registry
          name: jenkins-x-docker-registry
    - name: GIT_AUTHOR_EMAIL
      value: jenkins-x@googlegroups.com
    - name: GIT_AUTHOR_NAME
      value: jenkins-x-bot
    - name: GIT_COMMITTER_EMAIL
      value: jenkins-x@googlegroups.com
    - name: GIT_COMMITTER_NAME
      value: jenkins-x-bot
    - name: XDG_CONFIG_HOME
      value: /workspace/xdg_config
    - name: DOCKER_REGISTRY_ORG
      value: jstrachan-multicluster
    - name: BUILD_NUMBER
      value: "1"
    - name: PIPELINE_KIND
      value: release
    - name: REPO_OWNER
      value: jstrachan
    - name: REPO_NAME
      value: nodey442
    - name: JOB_NAME
      value: jstrachan/nodey442/master
    - name: APP_NAME
      value: nodey442
    - name: BRANCH_NAME
      value: master
    - name: JX_BATCH_MODE
      value: "true"
    - name: VERSION
      value: $(inputs.params.version)
    - name: BUILD_ID
      value: $(inputs.params.build_id)
    - name: PREVIEW_VERSION
      value: $(inputs.params.version)
    image: gcr.io/jenkinsxio/builder-jx:2.1.32-662
    name: git-merge
    resources:
      requests:
        cpu: 400m
        memory: 512Mi
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /home/jenkins
      name: workspace-volume
    - mountPath: /etc/podinfo
      name: podinfo
      readOnly: true
    workingDir: /workspace/source
  - args:
    - jx step git credentials
    command:
    - /bin/sh
    - -c
    env:
    - name: DOCKER_REGISTRY
      valueFrom:
        configMapKeyRef:
          key: docker.registry
          name: jenkins-x-docker-registry
    - name: GIT_AUTHOR_EMAIL
      value: jenkins-x@googlegroups.com
    - name: GIT_AUTHOR_NAME
      value: jenkins-x-bot
    - name: GIT_COMMITTER_EMAIL
      value: jenkins-x@googlegroups.com
    - name: GIT_COMMITTER_NAME
      value: jenkins-x-bot
    - name: XDG_CONFIG_HOME
      value: /workspace/xdg_config
    - name: DOCKER_REGISTRY_ORG
      value: jstrachan-multicluster
    - name: BUILD_NUMBER
      value: "1"
    - name: PIPELINE_KIND
      value: release
    - name: REPO_OWNER
      value: jstrachan
    - name: REPO_NAME
      value: nodey442
    - name: JOB_NAME
      value: jstrachan/nodey442/master
    - name: APP_NAME
      value: nodey442
    - name: BRANCH_NAME
      value: master
    - name: JX_BATCH_MODE
      value: "true"
    - name: VERSION
      value: $(inputs.params.version)
    - name: BUILD_ID
      value: $(inputs.params.build_id)
    - name: PREVIEW_VERSION
      value: $(inputs.params.version)
    image: gcr.io/jenkinsxio-labs-private/jxl:0.0.127
    name: setup-jx-git-credentials
    resources:
      requests:
        cpu: 400m
        memory: 512Mi
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /home/jenkins
      name: workspace-volume
    - mountPath: /etc/podinfo
      name: podinfo
      readOnly: true
    workingDir: /workspace/source
  - args:
    - jx step credential -s npm-token -k file -f /builder/home/.npmrc --optional=true
    command:
    - /bin/sh
    - -c
    env:
    - name: DOCKER_REGISTRY
      valueFrom:
        configMapKeyRef:
          key: docker.registry
          name: jenkins-x-docker-registry
    - name: GIT_AUTHOR_EMAIL
      value: jenkins-x@googlegroups.com
    - name: GIT_AUTHOR_NAME
      value: jenkins-x-bot
    - name: GIT_COMMITTER_EMAIL
      value: jenkins-x@googlegroups.com
    - name: GIT_COMMITTER_NAME
      value: jenkins-x-bot
    - name: XDG_CONFIG_HOME
      value: /workspace/xdg_config
    - name: DOCKER_REGISTRY_ORG
      value: jstrachan-multicluster
    - name: BUILD_NUMBER
      value: "1"
    - name: PIPELINE_KIND
      value: release
    - name: REPO_OWNER
      value: jstrachan
    - name: REPO_NAME
      value: nodey442
    - name: JOB_NAME
      value: jstrachan/nodey442/master
    - name: APP_NAME
      value: nodey442
    - name: BRANCH_NAME
      value: master
    - name: JX_BATCH_MODE
      value: "true"
    - name: VERSION
      value: $(inputs.params.version)
    - name: BUILD_ID
      value: $(inputs.params.build_id)
    - name: PREVIEW_VERSION
      value: $(inputs.params.version)
    image: gcr.io/jenkinsxio/builder-nodejs:2.1.32-662
    name: build-npmrc
    resources:
      requests:
        cpu: 400m
        memory: 512Mi
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /home/jenkins
      name: workspace-volume
    - mountPath: /etc/podinfo
      name: podinfo
      readOnly: true
    workingDir: /workspace/source
  - args:
    - npm install
    command:
    - /bin/sh
    - -c
    env:
    - name: DOCKER_REGISTRY
      valueFrom:
        configMapKeyRef:
          key: docker.registry
          name: jenkins-x-docker-registry
    - name: GIT_AUTHOR_EMAIL
      value: jenkins-x@googlegroups.com
    - name: GIT_AUTHOR_NAME
      value: jenkins-x-bot
    - name: GIT_COMMITTER_EMAIL
      value: jenkins-x@googlegroups.com
    - name: GIT_COMMITTER_NAME
      value: jenkins-x-bot
    - name: XDG_CONFIG_HOME
      value: /workspace/xdg_config
    - name: DOCKER_REGISTRY_ORG
      value: jstrachan-multicluster
    - name: BUILD_NUMBER
      value: "1"
    - name: PIPELINE_KIND
      value: release
    - name: REPO_OWNER
      value: jstrachan
    - name: REPO_NAME
      value: nodey442
    - name: JOB_NAME
      value: jstrachan/nodey442/master
    - name: APP_NAME
      value: nodey442
    - name: BRANCH_NAME
      value: master
    - name: JX_BATCH_MODE
      value: "true"
    - name: VERSION
      value: $(inputs.params.version)
    - name: BUILD_ID
      value: $(inputs.params.build_id)
    - name: PREVIEW_VERSION
      value: $(inputs.params.version)
    image: gcr.io/jenkinsxio/builder-nodejs:2.1.32-662
    name: build-npm-install
    resources:
      requests:
        cpu: 400m
        memory: 512Mi
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /home/jenkins
      name: workspace-volume
    - mountPath: /etc/podinfo
      name: podinfo
      readOnly: true
    workingDir: /workspace/source
  - args:
    - CI=true DISPLAY=:99 npm test
    command:
    - /bin/sh
    - -c
    env:
    - name: DOCKER_REGISTRY
      valueFrom:
        configMapKeyRef:
          key: docker.registry
          name: jenkins-x-docker-registry
    - name: GIT_AUTHOR_EMAIL
      value: jenkins-x@googlegroups.com
    - name: GIT_AUTHOR_NAME
      value: jenkins-x-bot
    - name: GIT_COMMITTER_EMAIL
      value: jenkins-x@googlegroups.com
    - name: GIT_COMMITTER_NAME
      value: jenkins-x-bot
    - name: XDG_CONFIG_HOME
      value: /workspace/xdg_config
    - name: DOCKER_REGISTRY_ORG
      value: jstrachan-multicluster
    - name: BUILD_NUMBER
      value: "1"
    - name: PIPELINE_KIND
      value: release
    - name: REPO_OWNER
      value: jstrachan
    - name: REPO_NAME
      value: nodey442
    - name: JOB_NAME
      value: jstrachan/nodey442/master
    - name: APP_NAME
      value: nodey442
    - name: BRANCH_NAME
      value: master
    - name: JX_BATCH_MODE
      value: "true"
    - name: VERSION
      value: $(inputs.params.version)
    - name: BUILD_ID
      value: $(inputs.params.build_id)
    - name: PREVIEW_VERSION
      value: $(inputs.params.version)
    image: gcr.io/jenkinsxio/builder-nodejs:2.1.32-662
    name: build-npm-test
    resources:
      requests:
        cpu: 400m
        memory: 512Mi
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /home/jenkins
      name: workspace-volume
    - mountPath: /etc/podinfo
      name: podinfo
      readOnly: true
    workingDir: /workspace/source
  - args:
    - /kaniko/executor --cache=true --cache-dir=/workspace --context=/workspace/source
      --dockerfile=/workspace/source/Dockerfile --destination=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION
      --cache-repo=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/cache
    command:
    - /busybox/sh
    - -c
    env:
    - name: DOCKER_REGISTRY
      valueFrom:
        configMapKeyRef:
          key: docker.registry
          name: jenkins-x-docker-registry
    - name: GIT_AUTHOR_EMAIL
      value: jenkins-x@googlegroups.com
    - name: GIT_AUTHOR_NAME
      value: jenkins-x-bot
    - name: GIT_COMMITTER_EMAIL
      value: jenkins-x@googlegroups.com
    - name: GIT_COMMITTER_NAME
      value: jenkins-x-bot
    - name: XDG_CONFIG_HOME
      value: /workspace/xdg_config
    - name: DOCKER_REGISTRY_ORG
      value: jstrachan-multicluster
    - name: BUILD_NUMBER
      value: "1"
    - name: PIPELINE_KIND
      value: release
    - name: REPO_OWNER
      value: jstrachan
    - name: REPO_NAME
      value: nodey442
    - name: JOB_NAME
      value: jstrachan/nodey442/master
    - name: APP_NAME
      value: nodey442
    - name: BRANCH_NAME
      value: master
    - name: JX_BATCH_MODE
      value: "true"
    - name: VERSION
      value: $(inputs.params.version)
    - name: BUILD_ID
      value: $(inputs.params.build_id)
    - name: PREVIEW_VERSION
      value: $(inputs.params.version)
    image: gcr.io/kaniko-project/executor:debug-v0.19.0
    name: build-container-build
    resources:
      requests:
        cpu: 400m
        memory: 512Mi
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /home/jenkins
      name: workspace-volume
    - mountPath: /etc/podinfo
      name: podinfo
      readOnly: true
    workingDir: /workspace/source
  - args:
    - cd /workspace/source/charts/nodey442 && jx step changelog --batch-mode --version
      v${VERSION}
    command:
    - /bin/sh
    - -c
    env:
    - name: DOCKER_REGISTRY
      valueFrom:
        configMapKeyRef:
          key: docker.registry
          name: jenkins-x-docker-registry
    - name: GIT_AUTHOR_EMAIL
      value: jenkins-x@googlegroups.com
    - name: GIT_AUTHOR_NAME
      value: jenkins-x-bot
    - name: GIT_COMMITTER_EMAIL
      value: jenkins-x@googlegroups.com
    - name: GIT_COMMITTER_NAME
      value: jenkins-x-bot
    - name: XDG_CONFIG_HOME
      value: /workspace/xdg_config
    - name: DOCKER_REGISTRY_ORG
      value: jstrachan-multicluster
    - name: BUILD_NUMBER
      value: "1"
    - name: PIPELINE_KIND
      value: release
    - name: REPO_OWNER
      value: jstrachan
    - name: REPO_NAME
      value: nodey442
    - name: JOB_NAME
      value: jstrachan/nodey442/master
    - name: APP_NAME
      value: nodey442
    - name: BRANCH_NAME
      value: master
    - name: JX_BATCH_MODE
      value: "true"
    - name: VERSION
      value: $(inputs.params.version)
    - name: BUILD_ID
      value: $(inputs.params.build_id)
    - name: PREVIEW_VERSION
      value: $(inputs.params.version)
    image: gcr.io/jenkinsxio-labs-private/jxl:0.0.127
    name: promote-changelog
    resources:
      requests:
        cpu: 400m
        memory: 512Mi
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /home/jenkins
      name: workspace-volume
    - mountPath: /etc/podinfo
      name: podinfo
      readOnly: true
    workingDir: /workspace/source
  - args:
    - cd /workspace/source/charts/nodey442 && jx step helm release
    command:
    - /bin/sh
    - -c
    env:
    - name: DOCKER_REGISTRY
      valueFrom:
        configMapKeyRef:
          key: docker.registry
          name: jenkins-x-docker-registry
    - name: GIT_AUTHOR_EMAIL
      value: jenkins-x@googlegroups.com
    - name: GIT_AUTHOR_NAME
      value: jenkins-x-bot
    - name: GIT_COMMITTER_EMAIL
      value: jenkins-x@googlegroups.com
    - name: GIT_COMMITTER_NAME
      value: jenkins-x-bot
    - name: XDG_CONFIG_HOME
      value: /workspace/xdg_config
    - name: DOCKER_REGISTRY_ORG
      value: jstrachan-multicluster
    - name: BUILD_NUMBER
      value: "1"
    - name: PIPELINE_KIND
      value: release
    - name: REPO_OWNER
      value: jstrachan
    - name: REPO_NAME
      value: nodey442
    - name: JOB_NAME
      value: jstrachan/nodey442/master
    - name: APP_NAME
      value: nodey442
    - name: BRANCH_NAME
      value: master
    - name: JX_BATCH_MODE
      value: "true"
    - name: VERSION
      value: $(inputs.params.version)
    - name: BUILD_ID
      value: $(inputs.params.build_id)
    - name: PREVIEW_VERSION
      value: $(inputs.params.version)
    image: gcr.io/jenkinsxio-labs-private/jxl:0.0.127
    name: promote-helm-release
    resources:
      requests:
        cpu: 400m
        memory: 512Mi
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /home/jenkins
      name: workspace-volume
    - mountPath: /etc/podinfo
      name: podinfo
      readOnly: true
    workingDir: /workspace/source
  - args:
    - cd /workspace/source/charts/nodey442 && jx promote -b --all-auto --timeout 1h
      --version ${VERSION}
    command:
    - /bin/sh
    - -c
    env:
    - name: DOCKER_REGISTRY
      valueFrom:
        configMapKeyRef:
          key: docker.registry
          name: jenkins-x-docker-registry
    - name: GIT_AUTHOR_EMAIL
      value: jenkins-x@googlegroups.com
    - name: GIT_AUTHOR_NAME
      value: jenkins-x-bot
    - name: GIT_COMMITTER_EMAIL
      value: jenkins-x@googlegroups.com
    - name: GIT_COMMITTER_NAME
      value: jenkins-x-bot
    - name: XDG_CONFIG_HOME
      value: /workspace/xdg_config
    - name: DOCKER_REGISTRY_ORG
      value: jstrachan-multicluster
    - name: BUILD_NUMBER
      value: "1"
    - name: PIPELINE_KIND
      value: release
    - name: REPO_OWNER
      value: jstrachan
    - name: REPO_NAME
      value: nodey442
    - name: JOB_NAME
      value: jstrachan/nodey442/master
    - name: APP_NAME
      value: nodey442
    - name: BRANCH_NAME
      value: master
    - name: JX_BATCH_MODE
      value: "true"
    - name: VERSION
      value: $(inputs.params.version)
    - name: BUILD_ID
      value: $(inputs.params.build_id)
    - name: PREVIEW_VERSION
      value: $(inputs.params.version)
    image: gcr.io/jenkinsxio-labs-private/jxl:0.0.127
    name: promote-jx-promote
    resources:
      requests:
        cpu: 400m
        memory: 512Mi
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /home/jenkins
      name: workspace-volume
    - mountPath: /etc/podinfo
      name: podinfo
      readOnly: true
    workingDir: /workspace/source
  volumes:
  - emptyDir: {}
    name: workspace-volume
  - downwardAPI:
      items:
      - fieldRef:
          fieldPath: metadata.labels
        path: labels
    name: podinfo
